//! `--completions <shell>`: the shell completion script, printed to stdout.
//!
//! Written out rather than generated by `clap_complete`, because there is no
//! clap here to generate from (D45) and the surface is three flags that take
//! no values. A generator would cost a dependency and a build script to
//! describe less than these thirty lines do.
//!
//! The scripts are what Homebrew installs through
//! `generate_completions_from_executable`, so the binary is the single source
//! for them; nothing in the tap or the release has to be kept in step.

/// The flags, in one place. Each script is checked against this list by the
/// tests, so a flag added to `main` and forgotten here does not go unnoticed.
pub const FLAGS: [(&str, &str); 4] = [
    ("--version", "Print the version and exit"),
    ("--help", "Print usage and exit"),
    (
        "--list-tools",
        "Print every tool this build offers and exit",
    ),
    ("--completions", "Print a shell completion script and exit"),
];

const BASH: &str = r#"_mcp_atlassian() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"
    if [[ "$prev" == "--completions" ]]; then
        COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
        return
    fi
    COMPREPLY=($(compgen -W "--version --help --list-tools --completions" -- "$cur"))
}
complete -F _mcp_atlassian mcp-atlassian
"#;

const ZSH: &str = r#"#compdef mcp-atlassian

_mcp_atlassian() {
    _arguments \
        '(- *)--version[Print the version and exit]' \
        '(- *)--help[Print usage and exit]' \
        '(- *)--list-tools[Print every tool this build offers and exit]' \
        '(- *)--completions[Print a shell completion script and exit]:shell:(bash zsh fish)'
}

_mcp_atlassian "$@"
"#;

const FISH: &str = r#"complete -c mcp-atlassian -f
complete -c mcp-atlassian -l version -d 'Print the version and exit'
complete -c mcp-atlassian -l help -d 'Print usage and exit'
complete -c mcp-atlassian -l list-tools -d 'Print every tool this build offers and exit'
complete -c mcp-atlassian -l completions -d 'Print a shell completion script and exit' -xa 'bash zsh fish'
"#;

/// The script for `shell`, or `None` if it is not one we write.
pub fn render(shell: &str) -> Option<&'static str> {
    match shell {
        "bash" => Some(BASH),
        "zsh" => Some(ZSH),
        "fish" => Some(FISH),
        _ => None,
    }
}

/// The shells above, for an error message that names them.
pub const SHELLS: [&str; 3] = ["bash", "zsh", "fish"];
