# Generated by the `homebrew` job in .github/workflows/ci.yml on every tag.
# Edit this template, not the copy in d3lph1/homebrew-tap — that one is
# overwritten by the next release.
class McpAtlassian < Formula
  desc "Lightweight MCP server for Jira and Confluence"
  homepage "https://github.com/d3lph1/mcp-atlassian"
  license "MIT"

  # The release ships bare binaries rather than archives, one per target;
  # each is the static build CI produced natively for that platform.
  on_macos do
    on_arm do
      url "https://github.com/d3lph1/mcp-atlassian/releases/download/v${VERSION}/mcp-atlassian-aarch64-apple-darwin"
      sha256 "${SHA_MACOS_ARM}"
    end
    on_intel do
      url "https://github.com/d3lph1/mcp-atlassian/releases/download/v${VERSION}/mcp-atlassian-x86_64-apple-darwin"
      sha256 "${SHA_MACOS_INTEL}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/d3lph1/mcp-atlassian/releases/download/v${VERSION}/mcp-atlassian-aarch64-unknown-linux-musl"
      sha256 "${SHA_LINUX_ARM}"
    end
    on_intel do
      url "https://github.com/d3lph1/mcp-atlassian/releases/download/v${VERSION}/mcp-atlassian-x86_64-unknown-linux-musl"
      sha256 "${SHA_LINUX_INTEL}"
    end
  end

  def install
    bin.install Dir["mcp-atlassian-*"].first => "mcp-atlassian"
    # A downloaded file is not executable the way a compiled one is, and the
    # next line has to run it. Without this the install fails with EACCES.
    chmod 0755, bin/"mcp-atlassian"
    # The binary prints its own completion scripts, so there is nothing to
    # keep in step between the release and the formula.
    generate_completions_from_executable(bin/"mcp-atlassian", "completions")
  end

  test do
    assert_match "mcp-atlassian #{version}", shell_output("#{bin}/mcp-atlassian --version")
    assert_match "complete", shell_output("#{bin}/mcp-atlassian completions bash")
    # Refuses to start unconfigured, and says which variables it wants.
    output = shell_output("#{bin}/mcp-atlassian 2>&1", 1)
    assert_match "JIRA_URL", output
  end
end
